// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Eretic431/fibonacci/config"
	"github.com/Eretic431/fibonacci/internal/fibonacci/delivery/grpc"
	"github.com/Eretic431/fibonacci/internal/fibonacci/delivery/http"
	"github.com/Eretic431/fibonacci/internal/fibonacci/usecase"
	"github.com/Eretic431/fibonacci/internal/server"
	"github.com/Eretic431/fibonacci/pkg/logger"
	"github.com/Eretic431/fibonacci/pkg/utils"
)

// Injectors from wire.go:

func initServer() (*server.Server, func(), error) {
	configConfig, err := config.GetConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, cleanup, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	fibonacciUseCase := usecase.NewFibonacciUseCase()
	fibonacciService := grpc.NewGrpcFibonacciService(fibonacciUseCase, sugaredLogger)
	httpHelper := utils.NewHttpHelper(sugaredLogger)
	httpFibonacciService := http.NewGrpcFibonacciService(fibonacciUseCase, sugaredLogger, httpHelper)
	serverServer := &server.Server{
		Log:         sugaredLogger,
		Cfg:         configConfig,
		GrpcService: fibonacciService,
		HttpService: httpFibonacciService,
	}
	return serverServer, func() {
		cleanup()
	}, nil
}
