version: '3'

services:

  app:
    container_name: fibonacci
    image: ghcr.io/eretic431/fibonacci
    restart: unless-stopped
    environment:
      - PRODUCTION=true
      - PORT=:8080
    ports:
      - 8080:8080